server:
  port: ${port}
spring:   
  application:
    name: PRODUCT-RETERIVE-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/groceryapp
#  data:
#    mongodb:
#      port: 27017
#      host: localhost
#      database: FullStack
  config:
    import: configserver:http://${host}:${portnum}
    
logging:
  level:
    root: info
    com: info
    
